name: Publish (Base)

on:
  workflow_call:
    inputs:
      modrinth-id:
        type: string
        required: false
      curseforge-id:
        type: string
        required: false
      version-type:
        type: string
        required: true
      minecraft-versions:
        type: string
        required: false
      java-version:
        type: number
        required: false
      mod-loaders:
        type: string
        required: false
      jitpack-safe-version:
        type: boolean
        required: false
    secrets:
      modrinth-token:
        required: false
      curseforge-token:
        required: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version || '21'}}
          distribution: "temurin"
          cache: "gradle"

      - name: Read mod version
        id: versions
        uses: BrycensRanch/read-properties-action@v1
        with:
          file: gradle.properties
          all: true

      - name: Read changelog
        uses: juliangruber/read-file-action@v1
        id: changelog
        with:
          path: "./changelog/${{ steps.versions.outputs.mod_version }}+${{ steps.versions.outputs.minecraft_version }}.md"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          name: "v${{ steps.versions.outputs.mod_version }} [${{ steps.versions.outputs.minecraft_version }}]"
          version: ${{ steps.versions.outputs.mod_version }}+mc.${{ steps.versions.outputs.minecraft_version }}
          version-type: ${{ inputs.version-type }}

          loaders: ${{ inputs.mod-loaders || 'fabric quilt'}}
          java: ${{ inputs.java-version || 17}}

          game-versions: ${{ inputs.minecraft-versions || steps.versions.outputs.minecraft_version }}
          changelog: ${{ steps.changelog.outputs.content }}

          modrinth-token: ${{ secrets.modrinth-token || '${undefined}' }}
          modrinth-id: ${{ inputs.modrinth-id }}
          modrinth-featured: false

          curseforge-token: ${{ secrets.curseforge-token || '${undefined}' }}
          curseforge-id: ${{ inputs.curseforge-id }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
          # We need to use boolean logic to fake a ternary operator
          github-tag: "${{ format('{0}{1}mc.{2}', steps.versions.outputs.mod_version, inputs.jitpack-safe-version && '-' || '+' , steps.versions.outputs.minecraft_version)}}"
          # Make sure we use the correct branch
          github-commitish: ${{ github.ref }}
