name: Sync Publishing Secrets
on: [workflow_dispatch]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: jpoehnelt/secrets-sync-action@v1.8.0
        with:
          github_token: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          secrets: |
            ^(MODRINTH|CURSEFORGE)_TOKEN$
          repositories: |
            MattiDragon/ExtendedDrawers
            MattiDragon/AdvancedNetworking
            MattiDragon/PowerNetworks
            MattiDragon/CustomDefaultWorldPreset
            MattiDragon/DemoBox
            MattiDragon/Nodeflow
            MattiDragon/JsonPatcher
            MattiDragon/GadgetsOfTheSky
            MattiDragon/TlaApi
            MattiDragon/PolydexBridge
            MattiDragon/UniversalPerms
            LordDeatHunter/FabricaeExNihilo
          repositories_list_regex: false
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
