name: Sync Publishing Secrets
on: [workflow_dispatch]
jobs:
  sync-secrets:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: google/secrets-sync-action@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
          SECRETS: |
            ^(MODRINTH|CURSEFORGE)_TOKEN$
          REPOSITORIES: |
            MattiDragon/ExtendedDrawers
            MattiDragon/AdvancedNetworking
            MattiDragon/PowerNetworks
            MattiDragon/CustomDefaultWorldPreset
            MattiDragon/DemoBox
            MattiDragon/Nodeflow
            MattiDragon/JsonPatcher
            LordDeatHunter/FabricaeExNihilo
          REPOSITORIES_LIST_REGEX: false
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
